### ISSUE TITLE
Integration with official Prometheus ruby client

### ISSUE THREAD

**Issue by duboff** [Strech/sidekiq-prometheus-exporter#19]
Thanks for the great gem. It worked like a charm.

I was, however, wondering if there was any best practice for integrating this with the official ruby client so that the `/metrics` endpoint exposes both Rails and Sidekiq metrics?

Appreciate any pointers.

**Comment by Strech** [comment]
You are welcome ❤️ 

Can you please clarify a bit what do you mean? Maybe you can share some examples or links? 

Official ruby client more/less do exactly the same, but with lots of additional functionality, you can create your own metrics and exporter can easily chip them in. If you mean something like "how can I chip in these metrics with my Rails metrics I already have" the answer will be not so easy.

The official client holds pre-aggregated counters/gauges, here we do on-demand computations. And if you run sidekiq as a separate service/process you just can't merge them together or we should use multi-process handler from official library

**Comment by Strech** [comment]
Hey @duboff, is everything fine? Does the answer close your question?

**Comment by duboff** [comment]
@Strech Yes, all good. It occured to me that it would be good to expose all metrics together, but we eventually decided to switch to Discourse's Prometheus exporter that does both Rails & Sidekiq metrics.

**Comment by Strech** [comment]
@duboff 👍 thanks
