### ISSUE TITLE
"FrozenError" in Rack 2.2

### ISSUE THREAD

**Issue by sobels** [Strech/sidekiq-prometheus-exporter#21]
Using this exporter on rack 2.2.2, I got the following stack trace on every request -

```
FrozenError (can't modify frozen Hash):
rack (2.2.2) lib/rack/etag.rb:35:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
(rest of the stack removed for brevity)
```

Now, according to rack's [changelog](https://github.com/rack/rack/blob/master/CHANGELOG.md) for 2.2.0,

> `Etag` will continue sending ETag even if the response should not be cached.

The problem is that `Rack::Etag` modifies a response's headers, and this exporter freezes its headers. The `no-cache` header used to prevent these two pieces of code from conflicting, but that's no longer the case.

Individual applications can work around this by deleting their `Rack::ETag` middleware, but that's probably not ideal. I would instead propose that we either make the exporter return non-frozen headers, or set a `Last-Modified` header equal to the current time. I can open a PR, but let me know if there's a specific approach you prefer.

**Comment by Strech** [comment]
Hey @sobels, thanks for your effort! I would say if we will add `Last-Modified` header, then we would need to modify the headers hash, then I would prefer no unfreeze it and allow `Rack` to add `Etag` key.

So yes, I would vote for unfreezing the headers hash 👍

**Comment by Strech** [comment]
@sobels Hey, for your convenience I've added `HEAD` test suite in [this branch](https://github.com/Strech/sidekiq-prometheus-exporter/tree/add-head-deps-build) feel free to use it for your adjustments.

In case if you don't have time, I can finish it as PR, just good to know do you have time or not?

**Comment by Strech** [comment]
@sobels Thanks for your effort, I release a fix as [v0.1.13](https://github.com/Strech/sidekiq-prometheus-exporter/releases/tag/v0.1.13) 🎉

**Comment by sobels** [comment]
Hey thanks for covering this, I totally forgot about it! 🍻

**Comment by Strech** [comment]
@sobels No worries 🥂
