### ISSUE TITLE
Operator to allow auto-monitoring of redis clusters defined in configs in K8s

### ISSUE THREAD

**Issue by mikhailadvani** [Strech/sidekiq-prometheus-exporter#28]
Problem:
When having multiple redis clusters in your infrastructure deploying the prometheus exporter efficiently can become a challenge. Redis configurations have to be duplicated for the helm-chart or whatever deployment mechanism and maintained.

Solution:
Kubernetes operator to watch Redis configurations used by applications

If we have labels/annotations on configmap/secret to allow/signal the operator to discover the redis configurations and create a set of resources(deployment, service, servicemonitor, etc) and wire into the prometheus-operator. Another advantage of the operator approach is to have the ability to handle updates & cleanups as well.

Thoughts?

If the solution plus #26 #27 is getting too kubernetes specific and you would like to move it to a separate repo, please advise how you would like to take this forward

**Comment by Strech** [comment]
@mikhailadvani Is it still relevant? Or I can close it?
