### ISSUE TITLE
Host helm chart repository

### ISSUE THREAD

**Issue by mikhailadvani** [Strech/sidekiq-prometheus-exporter#29]
Installing the chart from source in an automated way is not straightforward. It would be great to host the chart as an artefact somewhere like github pages. I am evaluating the solution and will share it shortly. Please share if you would like to host it in a different way

**Comment by Strech** [comment]
Sure, I will follow this guide after I finish shaping the chart: https://medium.com/containerum/how-to-make-and-share-your-own-helm-package-50ae40f6c221

**Comment by mikhailadvani** [comment]
or how about a github artefact like https://github.com/vmware/kube-fluentd-operator?

**Comment by Strech** [comment]
Can you elaborate on how do they do it?

**Comment by mikhailadvani** [comment]
Just a helm package and upload the artefact as a release asset. See: https://github.com/vmware/kube-fluentd-operator/releases
You can the install the chart using the tgz artefact as explained in the second snippet under https://github.com/vmware/kube-fluentd-operator#try-it-out

**Comment by Strech** [comment]
@mikhailadvani Thanks for your suggestion, it's now live 🎉 

P.S Unfortunately, all the tools are written for some specific workflow, so I end up with semi-manual upload which I will automate with Github Actions later. After I adjust main README section I will announce helm chart release 😉
