### ISSUE TITLE
Docker image does not work with Google Memorystore Redis instances

### ISSUE THREAD

**Issue by ckoenig** [Strech/sidekiq-prometheus-exporter#32]
The Docker image is using [Sidekiq 5.2.8](https://github.com/Strech/sidekiq-prometheus-exporter/blob/5ae01e936ab6b1f4772f2501e63dc3188084fb0c/docker/Dockerfile#L7). That version of Sidekiq still tries to set a client name for the Redis connection. This feature has been disabled by default in Sidekiq 6.0.7 by mperham/sidekiq#4479.

The problem is that SaaS providers, e.g. Google Cloud, might block calls to the `CLIENT` command in Redis. Thus `sidekiq-prometheus-exporter` fails to connect to Google Memorystore Redis instances.

There probably two options to fix this:
1. Update the sidekiq gem version used by the Docker image. However, I don't know if there was a specific reason to pick that version.
2. Update `config.ru` to handle some additional environment variable, e.g. `REDIS_DISABLE_ID`, and based on that add `id: nil` to the `config` hash for Sidekiq.

I'm happy to prepare a PR if needed. But I would need to know, what the preferred approach would be.

**Comment by Strech** [comment]
@ckoenig Hey! Yes, to `nil` the `id` is the correct approach 👍🏼 
Any help is welcome ❤️
