### ISSUE TITLE
Wrong redis URL when REDIS_HOST and REDIS_PASSWORD are used.

### ISSUE THREAD

**Issue by dcd000** [Strech/sidekiq-prometheus-exporter#33]
Redis url built at line 15 in docker/config.ru is missing the @ sign ending the password.

config[:url] = "redis://#{password}#{host}:#{port}/#{db_number}"

It should be:

config[:url] = "redis://#{password}@#{host}:#{port}/#{db_number}"

**Comment by Strech** [comment]
Hey @dcd000, thanks for spotting that. Will fix it ❤️

**Comment by Strech** [comment]
@dcd000 Fixed in [v0.1.14](https://github.com/Strech/sidekiq-prometheus-exporter/releases/tag/v0.1.14)
