### ISSUE TITLE
How to monitor more than one sidekiq redis in kubernetes 

### ISSUE THREAD

**Issue by sivakumar07** [Strech/sidekiq-prometheus-exporter#42]
We are running sidekiq for two services with two different redis instances. How to push the data and dashboard setup?

**Comment by Strech** [comment]
Hi @sivakumar07 not sure how your question is related to this project, but I will try to give you a general solution you can try out.

In Kubernetes you can have Sidekiq pod which will consist of 2 containers: Sidekiq + Sidekiq metrics. And then you enable prometheus to scrape both. You differentiate them by labels your Prometheus scrapper will add.

If you have a specific issue with `sidekiq-prometheus-exporter` please elaborate
