### ISSUE TITLE
Retry by queue gauge?

### ISSUE THREAD

**Issue by neuromantik33** [Strech/sidekiq-prometheus-exporter#49]
Is there anyway to have a time series the number of retries per queue? Thanks in advance.

**Comment by Strech** [comment]
Hi @neuromantik33 as I understand your request you would like to collect retries of the jobs per queue? The problem with such thing is that to measure it – you will have to collect that metric on the worker and expose it later to outside.

Currently Sidekiq counting only failed jobs (exhausted retries) and to gather metric you want you will need to use another gem which allows you to have as custom metric (with custom logic) and expose it for Prometheus, for instance with official gem https://github.com/prometheus/client_ruby

**Comment by Strech** [comment]
Hey @neuromantik33 I going to close this issue if you have any questions or want to elaborate – feel free to reopen it
