### ISSUE TITLE
Allow to add custom tag

### ISSUE THREAD

**Issue by hannan228** [Strech/sidekiq-prometheus-exporter#51]
Hi, Thanks for this gem,
What about if some one wants to add custom tags as this [yabeda-sidekiq](https://github.com/yabeda-rb/yabeda-sidekiq) gem is allowing.

**Comment by Strech** [comment]
Hi @hannan228, I think it could be done to some extent. 

The main difference between `yabeda-sidekiq` and this exporter is a collector (shared storage used to expose metrics later). We don't have it; hence, there is no way to have exactly the same functionality (assign custom labels from the local code). Instead, as a trade-off – this exporter offers a very straightforward and fast way to bet all the essential metrics out of the sidekiq.

What could be done - we can add a configuration option to add any labels to the metrics, which could be configured in your `config.ru` or so, but I think it will duplicate the correct way of doing so – a Prometheus configuration.
