### ISSUE TITLE
Support usernames in Redis

### ISSUE THREAD

**Issue by pznamensky** [Strech/sidekiq-prometheus-exporter#57]
Redis 6 and later has improved ACL with more granular access: https://redis.io/docs/management/security/acl/
However, the exporter doesn't support the new schema.
It would be really cool to add username support:
- probably an env variable `REDIS_USERNAME`
- and a new url format: `#{scheme}://#{username}:#{password}@#{host}:#{port}/#{db_number}`

**Comment by pznamensky** [comment]
Hey @Strech, thanks for the idea!
Also, I would be happy to test pre-release version if you want.

**Comment by pznamensky** [comment]
Hey @Strech, can I help you somehow from my side?

**Comment by Strech** [comment]
Hey @pznamensky I've got sucked by work 😄 

Yes, I would appreciate your help with it. We can do it together if you want. It would be cool if you can introduce the variable and sprinkle that knowledge into docs and I will take care of correcting/releasing. WDYT?

**Comment by pznamensky** [comment]
I tried to add a new environment variable and change corresponding `config[:url]`, but something didn't work for me. Unfortunately, I don't know Ruby well enough to fix it 🙈 

The good news is that we can actually pass username and password pair directly in the `REDIS_URL`.
In case somebody wants configure Redis for the exporter too, the user requires the following permissions:
`+client +ping +info +get +zcard +scard +llen +lrange +sscan +set +hget +hmget +exists +hgetall ~* &*`

@Strech Thank you for the help!

**Comment by Strech** [comment]
Hey @pznamensky forry for a long response time, the new version of Docker image with all dependencies updated was released!

You can get it with this command

```
docker pull strech/sidekiq-prometheus-exporter:0.2.0
```

And it supports `REDIS_USERNAME` environment variable. Enjoy 🎉

**Comment by pznamensky** [comment]
Great job! @Strech thank you!
