### ISSUE TITLE
Couldn't find handler

### ISSUE THREAD

**Issue by ChadOhman** [Strech/sidekiq-prometheus-exporter#59]
Since the release yesterday, the Docker container is erroring and restarting:
```
/usr/local/bundle/gems/rack-2.2.6.4/lib/rack/handler.rb:45:in `pick': Couldn't find handler for: puma, thin, falcon, webrick. (LoadError)
	from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/handler.rb:60:in `default'
	from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/server.rb:334:in `server'
	from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/server.rb:327:in `start'
	from /usr/local/bundle/gems/rack-2.2.6.4/lib/rack/server.rb:168:in `start'
	from /usr/local/bundle/gems/rack-2.2.6.4/bin/rackup:5:in `<top (required)>'
	from /usr/local/bundle/bin/rackup:25:in `load'
	from /usr/local/bundle/bin/rackup:25:in `<main>'
```
I've updated the REDIS_URL to append /0 but that hasn't worked. I'm not sure if #57 is related to this?

My environment variables:
![image](https://user-images.githubusercontent.com/2351/233821660-c9105c72-c4ce-49d6-958c-d974b0a14d77.png)

Thanks for any help you can provide.

**Comment by Strech** [comment]
Hey folks, I accidentally broke it by updating Ruby to 3.x were Webrick was pulled out as a separate gem. It got fixed in Docker [0.2.0-1](https://github.com/Strech/sidekiq-prometheus-exporter/releases/tag/v0.2.0-1)

```console
docker pull strech/sidekiq-prometheus-exporter:0.2.0-1
```
