### ISSUE TITLE
Invalid content-length being periodically returned

### ISSUE THREAD

**Issue by ThisIsMissEm** [Strech/sidekiq-prometheus-exporter#67]
For some reason this is returning a 500 error for us periodically with:

```
content-length header was 3842, but should be 3905
```

We're deploying via rackup and webrick: https://github.com/hachyderm/sidekiq-prometheus-exporter

Not sure why we'd be getting an incorrect content-length back from this?

**Comment by ThisIsMissEm** [comment]
After reviewing the code further, I'm wondering if it's because we're letting webrick/rackup automatically set the content length?

e.g., maybe the Sidekiq::Prometheus::Exporter.call method needs to set content-length based on `EXPORTERS.to_s`'s byte length?

**Comment by Strech** [comment]
Hey @ThisIsMissEm thanks for reporting. Let me investigate it a bit.

Do I understand it correctly, when I request `/metrics` [here](https://github.com/hachyderm/sidekiq-prometheus-exporter) I suppose to see this issue?

**Comment by ThisIsMissEm** [comment]
Correct! It happens with some frequency, though I'm not sure what frequency that is.

**Comment by Strech** [comment]
@evantissot @ThisIsMissEm can you share the setup you run it

1. ruby version
2. gems versions (probably `bundle list`)
3. Any other setup specific thing you think is important

I would try investigate it. An important part is to see the Ruby and Rack version you use and maybe the webserver.

Thanks! 💜

**Comment by ThisIsMissEm** [comment]
```
$ ruby -v
ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]
```

(we could also switch to ruby via rbenv for 3.3.5)

```
Gems included by the bundle:
  * connection_pool (2.4.1)
  * dotenv (3.1.4)
  * logger (1.6.1)
  * rack (3.1.8)
  * rackup (2.1.0)
  * redis-client (0.22.2)
  * sidekiq (7.3.4)
  * sidekiq-prometheus-exporter (0.2.0)
  * webrick (1.8.2)
Use `bundle info` to print more detailed information about a gem
```

We are using vendored gems:

```
sidekiq-prometheus-exporter/
├── etc
│   └── systemd
│       └── system
└── vendor
    └── bundle
        └── ruby
            └── 3.2.0
                ├── bin
                ├── build_info
                ├── cache
                ├── doc
                ├── extensions
                ├── gems
                │   ├── connection_pool-2.4.1
                │   ├── dotenv-3.1.4
                │   ├── logger-1.6.1
                │   ├── rack-3.1.8
                │   ├── rackup-2.1.0
                │   ├── redis-client-0.22.2
                │   ├── sidekiq-7.3.4
                │   ├── sidekiq-prometheus-exporter-0.2.0
                │   └── webrick-1.8.2
                ├── plugins
                └── specifications
```

**Comment by evantissot** [comment]
Here is our setup 

```
$ ruby -v
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux-musl]
```

```
rack (3.1.8)
rackup (2.1.0)
redis-client (0.22.2)
sidekiq (7.3.2)
sidekiq-prometheus-exporter (0.2.0)
webrick (1.8.2)
```

**Comment by Strech** [comment]
I have the luck to reproduce the error you're getting with gem versions of your setup @ThisIsMissEm 

```
system-test-metrics-1  | 172.19.0.1 - - [03/Nov/2024:20:22:31 +0000] "GET /metrics HTTP/1.1" 200 4683 0.0090
system-test-metrics-1  | [2024-11-03 20:22:31] ERROR Rack::Lint::LintError: content-length header was 4683, but should be 4755
```

Let me digg a bit in to understand the source of the issue

**Comment by ThisIsMissEm** [comment]
Aha! Fantastic! Thank you 😊
